### PR TITLE
(typo) Minor correction

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by larzw** [comment]
Thanks @gep13!

FYI I've got a [Codov](https://codecov.io/gh) cake addin in the works. Just need to finish the exe [uploader](https://github.com/codecov/codecov-exe) for their api.

**Comment by gep13** [comment]
@larzw noice! That has been on my list of things to look at.  Currently using Coveralls.io.  Let me know when you have something ready, would like to take a look at it.

**Comment by AdmiringWorm** [comment]
@larzw just curious, how is it going with the cake codecov addin?
I was just about to start on my own, when @gep13 told me you were already working on one.

**Comment by gep13** [comment]
@larzw @AdmiringWorm if this is something that you would both want to work on, would it make sense to host the repository under the cake-contrib organisation, where I could add you both as administrators, with full rights to the repository?

Thank you both for your interest in creating this addin.

**Comment by larzw** [comment]
Hi @AdmiringWorm, I'm currently writing the codecov uploader (#tool for cake script). It's almost done. Steve (the author of codecov) is reviewing it now and has plans to put it into production. I've got something very basic worked out for the addin. 

@gep13 I think that is a great idea to host the addin under the cake-contrib organization. I can add my preliminary code on there. I can also create and add everyone as an owner for the nuget package. Is everyone ok with that idea?

**Comment by gep13** [comment]
>@larzw said...
I can also create and add everyone as an owner for the nuget package. Is everyone ok with that idea?

That would be perfect!  From the Cake Team side of things, adding the cake-contrib user as a co-owner of the package is all that would be required.

Once moved into the cake-contrib organisation, I can set up the AppVeyor CI builds, etc.

@larzw thanks for your help on this!

**Comment by AdmiringWorm** [comment]
> I can also create and add everyone as an owner for the nuget package. Is everyone ok with that idea?

I'm okay with that. Although, if you have most planned out already there probably won't be a need for me, but I'll help out wherever I can.

**Pull request merged**
